apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-conf
  namespace: suite
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_type all
