apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-dnsmasq-custom
  namespace: suite
data:
  03-custom.conf: |
    address=/suite.home.arpa/192.168.50.242
    host-record=mirror.suite.home.arpa,192.168.50.242
    host-record=homebridge.suite.home.arpa,192.168.50.242
    host-record=scrypted.suite.home.arpa,192.168.50.242
    host-record=pi.hole,192.168.50.245
