# ===== Zigbee2MQTT + Longhorn Snapshot Toolkit ===============================
# Prereqs: kubectl, jq
# Override any var on the CLI, e.g. `make snap NS=my-namespace`
# -----------------------------------------------------------------------------
SHELL := /usr/bin/env bash
.SHELLFLAGS := -eu -o pipefail -c

# ---- Tunables ---------------------------------------------------------------
NS             ?= suite
APP            ?= zigbee2mqtt
DEPLOY         ?= $(APP)
PVC            ?= zigbee2mqtt-data
VOLUME_NAME    ?= data                 # name of the volume in the Deployment spec
SC             ?= longhorn
SNAPCLASS      ?= longhorn-snap
SNAPSHOTTER_TAG ?= release-6.3
LH_NS          ?= longhorn-system

# Autogenerated names (can be overridden)
NOW           := $(shell date +%Y%m%d-%H%M)
SNAP          ?= $(APP)-snap-$(NOW)
RESTPVC       ?= $(PVC)-restore-$(shell date +%H%M)

K = kubectl -n $(NS)

# ---- Help -------------------------------------------------------------------
.PHONY: help
help:
	@echo ""
	@echo "Targets:"
	@echo "  deps                      - check for kubectl + jq"
	@echo "  install-snapshotter       - install CSI snapshot CRDs + controller (cluster-wide)"
	@echo "  snapclass                 - create VolumeSnapshotClass '$(SNAPCLASS)' for Longhorn"
	@echo "  snap [SNAP=...]           - create a VolumeSnapshot from PVC '$(PVC)' -> name '$(SNAP)'"
	@echo "  snap-wait [SNAP=...]      - show snapshot status & readyToUse"
	@echo "  restore [SNAP=...]        - create PVC clone '$(RESTPVC)' from snapshot"
	@echo "  verify-restore [RESTPVC=...] - mount restored PVC in temp pod and list files"
	@echo "  rollback [RESTPVC=...]    - switch Deployment '$(DEPLOY)' volume '$(VOLUME_NAME)' to restored PVC"
	@echo "  hourly-schedule           - enable hourly snapshots (retain 24) on '$(PVC)'"
	@echo "  nightly-backup            - create nightly backup RecurringJob (retain 7) (requires backup target configured in Longhorn)"
	@echo "  ember-switch              - change Z2M adapter in configuration.yaml from ezsp -> ember"
	@echo "  pin-digest                - pin Deployment image to the currently running digest"
	@echo ""
	@echo "Examples:"
	@echo "  make install-snapshotter snapclass"
	@echo "  make snap"
	@echo "  make restore SNAP=$(APP)-snap-20251111-1444"
	@echo "  make verify-restore RESTPVC=$(PVC)-restore-0938"
	@echo "  make rollback RESTPVC=$(PVC)-restore-0938"
	@echo ""

# ---- Sanity: deps -----------------------------------------------------------
.PHONY: deps
deps:
	@command -v kubectl >/dev/null 2>&1 || { echo "kubectl not found"; exit 1; }
	@command -v jq >/dev/null 2>&1 || { echo "jq not found"; exit 1; }
	@echo "deps OK"

# ---- Install CSI snapshot API + controller ----------------------------------
.PHONY: install-snapshotter
install-snapshotter: deps
	kubectl kustomize "https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=$(SNAPSHOTTER_TAG)" | kubectl apply -f -
	kubectl kustomize "https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=$(SNAPSHOTTER_TAG)" \
	  | sed 's/namespace: default/namespace: kube-system/g' | kubectl apply -f -
	@echo "Installed snapshot-controller (kube-system):"
	@kubectl -n kube-system get deploy | grep snapshot-controller || true

# ---- VolumeSnapshotClass for Longhorn ---------------------------------------
.PHONY: snapclass
snapclass:
	@cat <<'YAML' | kubectl apply -f -
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: $(SNAPCLASS)
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
YAML
	@kubectl get volumesnapshotclass

# ---- Create snapshot --------------------------------------------------------
.PHONY: snap
snap: deps
	@echo "Creating VolumeSnapshot $(SNAP) from PVC $(PVC) in $(NS)"
	@cat <<YAML | $(K) apply -f -
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: $(SNAP)
  namespace: $(NS)
spec:
  volumeSnapshotClassName: $(SNAPCLASS)
  source:
    persistentVolumeClaimName: $(PVC)
YAML
	@$(K) get volumesnapshot $(SNAP) -o wide || true

.PHONY: snap-wait
snap-wait:
	@echo -n "readyToUse: "; $(K) get volumesnapshot $(SNAP) -o jsonpath='{.status.readyToUse}{"\n"}' || true
	@$(K) get volumesnapshot $(SNAP) -o wide || true

# ---- Restore snapshot to a new PVC ------------------------------------------
.PHONY: restore
restore: deps
	@test -n "$(SNAP)" || (echo "SNAP var required"; exit 1)
	@echo "Restoring $(SNAP) -> PVC $(RESTPVC)"
	@cat <<YAML | $(K) apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $(RESTPVC)
  namespace: $(NS)
spec:
  storageClassName: $(SC)
  dataSource:
    name: $(SNAP)
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
YAML
	@$(K) get pvc $(RESTPVC) -o wide

# ---- Verify contents of restored PVC ----------------------------------------
.PHONY: verify-restore
verify-restore: deps
	@test -n "$(RESTPVC)" || (echo "RESTPVC var required"; exit 1)
	@cat <<YAML | $(K) apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: z2m-restore-check
  namespace: $(NS)
spec:
  restartPolicy: Never
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: $(RESTPVC)
  containers:
  - name: s
    image: busybox:stable
    command: ["sh","-lc"]
    args: ["set -eux; echo Mounted; mount | grep /app/data || true; ls -l /app/data | head -n 50; sleep 600"]
    volumeMounts:
    - name: data
      mountPath: /app/data
YAML
	@$(K) wait --for=condition=ready pod/z2m-restore-check --timeout=90s
	@$(K) exec -it z2m-restore-check -- sh -lc 'mount | grep /app/data; ls -l /app/data | head -n 50'
	@$(K) delete pod z2m-restore-check --wait=true

# ---- Rollback deploy to a restored PVC --------------------------------------
.PHONY: rollback
rollback: deps
	@test -n "$(RESTPVC)" || (echo "RESTPVC var required"; exit 1)
	@echo "Scaling $(DEPLOY) to 0..."
	@$(K) scale deploy/$(DEPLOY) --replicas=0
	@$(K) wait --for=delete pod -l app=$(APP) --timeout=120s || true
	@echo "Finding volume index for '$(VOLUME_NAME)'..."
	@IDX=$$($(K) get deploy $(DEPLOY) -o json | jq -r '.spec.template.spec.volumes | to_entries[] | select(.value.name=="$(VOLUME_NAME)") | .key'); \
	  if [[ -z $$IDX ]]; then echo "Volume '$(VOLUME_NAME)' not found in Deployment"; exit 1; fi; \
	  echo "Patching index $$IDX to PVC '$(RESTPVC)'..."; \
	  $(K) patch deploy $(DEPLOY) --type='json' -p="[{\"op\":\"replace\",\"path\":\"/spec/template/spec/volumes/$$IDX/persistentVolumeClaim/claimName\",\"value\":\"$(RESTPVC)\"}]"
	@echo "Scaling $(DEPLOY) to 1..."
	@$(K) scale deploy/$(DEPLOY) --replicas=1
	@$(K) wait --for=condition=available deploy/$(DEPLOY) --timeout=180s
	@$(K) logs deploy/$(DEPLOY) --tail=80

# ---- Recurring jobs (hourly snapshots) --------------------------------------
.PHONY: hourly-schedule
hourly-schedule:
	@echo "Create/ensure RecurringJob z2m-hourly-snap (Longhorn)"
	@cat <<'YAML' | kubectl -n $(LH_NS) apply -f -
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: z2m-hourly-snap
  namespace: $(LH_NS)
spec:
  cron: "0 * * * *"   # hourly
  task: snapshot
  retain: 24
  concurrency: 1
  groups:
  - default
YAML
	@echo "Attach job to PVC $(PVC)"
	@$(K) label pvc/$(PVC) recurring-job.longhorn.io/source=enabled --overwrite
	@$(K) label pvc/$(PVC) recurring-job.longhorn.io/z2m-hourly-snap=enabled --overwrite
	@$(K) describe pvc/$(PVC) | sed -n '/Annotations:/,/Volume Name:/p' || true

# ---- Nightly backups (requires Longhorn backup target configured) -----------
.PHONY: nightly-backup
nightly-backup:
	@cat <<'YAML' | kubectl -n $(LH_NS) apply -f -
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: z2m-nightly-backup
  namespace: $(LH_NS)
spec:
  cron: "0 3 * * *"   # 03:00 daily
  task: backup
  retain: 7
  concurrency: 1
  groups:
  - default
YAML
	@$(K) label pvc/$(PVC) recurring-job.longhorn.io/z2m-nightly-backup=enabled --overwrite
	@$(K) describe pvc/$(PVC) | sed -n '/Annotations:/,/Volume Name:/p' || true

# ---- Switch Z2M adapter: ezsp -> ember --------------------------------------
.PHONY: ember-switch
ember-switch:
	@POD=$$($(K) get pods -l app=$(APP) --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}'); \
	  if [[ -z $$POD ]]; then echo "No running pod for $(APP)"; exit 1; fi; \
	  echo "Switching adapter to ember in /app/data/configuration.yaml"; \
	  $(K) exec $$POD -- sh -lc "sed -i 's/^\\s*adapter:\\s*ezsp/  adapter: ember/' /app/data/configuration.yaml || true"
	@$(K) rollout restart deploy/$(DEPLOY)
	@$(K) wait --for=condition=available deploy/$(DEPLOY) --timeout=180s
	@$(K) logs deploy/$(DEPLOY) --tail=60

# ---- Pin current image digest (good hygiene) --------------------------------
.PHONY: pin-digest
pin-digest:
	@POD=$$($(K) get pods -l app=$(APP) -o jsonpath='{.items[0].metadata.name}'); \
	  if [[ -z $$POD ]]; then echo "No pod found"; exit 1; fi; \
	  DIGEST=$$($(K) get pod $$POD -o jsonpath='{.status.containerStatuses[0].imageID}' | sed 's|^docker-pullable://||'); \
	  IMGNAME=$$($(K) get deploy $(DEPLOY) -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d@ -f1); \
	  echo "Pinning $$IMGNAME to $$DIGEST"; \
	  $(K) set image deploy/$(DEPLOY) $(APP)=$$DIGEST; \
	  $(K) rollout status deploy/$(DEPLOY) --timeout=180s


