apiVersion: v1
kind: Pod
metadata:
  name: nvme-check
spec:
  restartPolicy: Never
  containers:
    - name: busy
      image: busybox:stable
      command: ["sh", "-c", "mount | grep longhorn && df -h && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-nvme-pvc

