#!/usr/bin/env bash
set -euo pipefail

# --- Config you may adjust ---
KUBECONFIG_PATH="${KUBECONFIG:-$HOME/.kube/config}"
DEFAULT_API="https://192.168.50.251:6443"
CONTROL_PLANES=("m1" "m2" "m3")
REMOTE_TOKEN_PATH="/var/lib/rancher/k3s/server/node-token"
AUTO_TFVARS="terraform.auto.tfvars"

echo "🔍 Discovering k3s_url from kubeconfig..."
K3S_URL=$(kubectl --kubeconfig "$KUBECONFIG_PATH" config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null || true)
if [[ -z "${K3S_URL}" ]]; then
  echo "⚠️  Falling back to ${DEFAULT_API}"
  K3S_URL="$DEFAULT_API"
fi
echo "➡️  k3s_url=${K3S_URL}"

echo "🔑 Fetching k3s_token from control-plane..."
K3S_TOKEN=""
for host in "${CONTROL_PLANES[@]}"; do
  if TOKEN=$(ssh "$host" "sudo cat ${REMOTE_TOKEN_PATH}" 2>/dev/null); then
    K3S_TOKEN="$TOKEN"
    echo "➡️  Retrieved token from ${host}"
    break
  else
    echo "   (skip ${host})"
  fi
done
if [[ -z "${K3S_TOKEN}" ]]; then
  echo "❌ Could not retrieve K3s token automatically. You can manually set it later."
fi

echo "🌐 Detecting public IP..."
PUB_IP=$(curl -s https://ifconfig.me || curl -s https://api.ipify.org || true)
if [[ -n "${PUB_IP}" ]]; then
  AWS_ALLOWED_CIDR="${PUB_IP}/32"
  echo "➡️  aws_allowed_cidr=${AWS_ALLOWED_CIDR}"
else
  AWS_ALLOWED_CIDR="192.168.50.0/24"
  echo "⚠️  Could not detect public IP. Using LAN CIDR ${AWS_ALLOWED_CIDR}"
fi

# Suggest common values
CLUSTER_LAN_CIDR="192.168.50.0/24"
METALLB_POOL="192.168.50.241-192.168.50.251"

echo "📝 Writing ${AUTO_TFVARS}..."
cat > "${AUTO_TFVARS}" <<EOF
# Auto-generated by scripts/gather.sh — review & tweak!

k3s_url         = "${K3S_URL}"
k3s_token       = "${K3S_TOKEN}"
kubeconfig_path = "${KUBECONFIG_PATH}"
cluster_name    = "smart-kube"
cluster_lan_cidr = "${CLUSTER_LAN_CIDR}"

aws_profile      = "default"
aws_region       = "us-east-1"
aws_key_name     = "allenwayne-main"
aws_allowed_cidr = "${AWS_ALLOWED_CIDR}"
aws_vpc_cidr     = "10.42.0.0/16"
aws_public_subnets  = ["10.42.1.0/24","10.42.2.0/24"]
aws_private_subnets = ["10.42.101.0/24","10.42.102.0/24"]
aws_eks_enable   = false
aws_ec2_enable   = false

tags = { Project = "iot", Owner = "allenwayne", Env = "home" }

metallb_address_pool = ["${METALLB_POOL}"]
ingress_class        = "traefik"
external_dns_provider = "cloudflare"

domain_name = "allenwmoorejr.org"
dns_zone_id = "REPLACE_WITH_ZONE_ID"
acme_email  = "allenwmoorejr@outlook.com"
acme_env    = "prod"

registry_server   = "index.docker.io"
registry_username = "allenwayne"
registry_password = "REPLACE_WITH_TOKEN"
gitops_repo_url   = "https://github.com/allenwmoorejr/smart-kube.git"
gitops_branch     = "main"

monitoring_enable       = true
grafana_admin_user      = "admin"
grafana_admin_password  = "REPLACE_ME"
EOF

echo "✅ Created ${AUTO_TFVARS}. Next: 'terraform init && terraform plan'"

