# Auto-generated by scripts/gather.sh — review & tweak!

k3s_url          = "https://m2:6443"
k3s_token        = "K1015a839a471a9ab52e72e555ab44e4b3c074bd4e794633d4654b38ff01abed311::server:254b5280dc316dac0b517d994d7f6174"
kubeconfig_path  = "/home/wayne/.kube/config"
cluster_name     = "smart-kube"
cluster_lan_cidr = "192.168.50.0/24"

aws_profile         = "default"
aws_region          = "us-east-1"
aws_key_name        = "allenwayne-main"
aws_allowed_cidr    = "99.104.135.61/32"
aws_vpc_cidr        = "10.42.0.0/16"
aws_public_subnets  = ["10.42.1.0/24", "10.42.2.0/24"]
aws_private_subnets = ["10.42.101.0/24", "10.42.102.0/24"]
aws_eks_enable      = false
aws_ec2_enable      = false

tags = { Project = "iot", Owner = "allenwayne", Env = "home" }

metallb_address_pool  = ["192.168.50.241-192.168.50.251"]
ingress_class         = "traefik"
external_dns_provider = "cloudflare"

domain_name = "allenwmoorejr.org"
dns_zone_id = "REPLACE_WITH_ZONE_ID"
acme_email  = "allenwmoorejr@outlook.com"
acme_env    = "prod"

registry_server   = "index.docker.io"
registry_username = "allenwayne"
registry_password = "REPLACE_WITH_TOKEN"
gitops_repo_url   = "https://github.com/allenwmoorejr/smart-kube.git"
gitops_branch     = "main"

monitoring_enable      = true
grafana_admin_user     = "admin"
grafana_admin_password = "REPLACE_ME"
