# Auto-generated by scripts/gather.sh — review & tweak!

k3s_url = "https://100.83.32.8:6443"  # control-plane’s Tailscale IP
k3s_token = "K1015a839a471a9ab52e72e555ab44e4b3c074bd4e794633d4654b38ff01abed311::server:254b5280dc316dac0b517d994d7f6174"

# access
aws_profile      = "default"
aws_region       = "us-east-1"
aws_key_name     = "allenwayne-main"
aws_allowed_cidr = "99.104.135.61/32"
my_ip_cidr       = "99.104.135.61/32"

# worker identity
worker_name        = "cloud-worker-1"
tailscale_auth_key = "tskey-xxxxx" # or use env: TF_VAR_tailscale_auth_key

# dns / certs
domain_name = "allenwmoorejr.org"
dns_zone_id = "6f93844289a79b0a6e48178655cafc62"
acme_email  = "allenwmoorejr@outlook.com"
acme_env    = "prod"

# addons
metallb_address_pool  = ["192.168.50.241-192.168.50.251"]
ingress_class         = "traefik"
external_dns_provider = "cloudflare"

# registry / gitops (optional; remove if unused)
registry_server   = "index.docker.io"
registry_username = "allenwayne"
registry_password = "dckr_pat_********" # consider env var instead
gitops_repo_url   = "https://github.com/allenwmoorejr/smart-kube.git"
gitops_branch     = "main"

# tagging
tags            = { Project = "iot", Owner = "allenwayne", Env = "home" }
kubeconfig_path = "/home/wayne/.kube/config"
