apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data
  namespace: suite
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-backups
  namespace: suite
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 2Gi } }
  storageClassName: local-path
