apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data-longhorn
  namespace: suite
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-backups-longhorn
  namespace: suite
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 2Gi } }
  storageClassName: longhorn
