apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magicmirror-data
  namespace: suite
spec:
  accessModes:
    - ReadWriteMany   # RWX so multiple replicas can share
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi     # tweak as you like
  volumeMode: Filesystem

