apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mm-modules-pvc
  namespace: suite
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

