{{- if .Values.spotify.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: spotify-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  clientId: "{{ .Values.spotify.clientId }}"
  clientSecret: "{{ .Values.spotify.clientSecret }}"
  accessToken: "{{ .Values.spotify.accessToken }}"
  refreshToken: "{{ .Values.spotify.refreshToken }}"
{{- end }}
