apiVersion: v1
kind: Service
metadata:
  name: magicmirror-hostport
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: magicmirror-server
  ports:
    - name: ui
      port: {{ .Values.service.port }}
      targetPort: 8080
