et -euo pipefail

REPO_SSH="git@github.com:allenwmoorejr/iot.git"
BRANCH="feature/micro-cam-rtsp-tcp-longhorn"
WORKDIR="${HOME}/tmp/iot-rtsp-update"

rm -rf "$WORKDIR"
mkdir -p "$WORKDIR"
cd "$WORKDIR"

echo "===> Cloning ${REPO_SSH}"
git clone "$REPO_SSH" .
git checkout -b "$BRANCH"

# Paths used in your repo layout
# APP_DIR="30-apps/micro-cam"
# K8S_DIR="${APP_DIR}/k8s"
# DOCS_DIR="docs/storage"
# TRAEFIK_DIR="kube-system/traefik"
# LONGHORN_DIR="infra/longhorn"
#
# mkdir -p "$K8S_DIR" "$DOCS_DIR" "$TRAEFIK_DIR" "$LONGHORN_DIR"
#
# # --- 1) Traefik TCP entrypoint for RTSP (:8554) ---
# cat > "${TRAEFIK_DIR}/traefik-tcp-entrypoint.yaml" <<'YAML'
# apiVersion: helm.cattle.io/v1
# kind: HelmChartConfig
# metadata:
#   name: traefik
#     namespace: kube-system
#     spec:
#       valuesContent: |-
#           additionalArguments:
#                 - "--entrypoints.rtsp.address=:8554/tcp"
#                     ports:
#                           rtsp:
#                                   port: 8554
#                                           expose: true
#                                                   protocol: TCP
#                                                   YAML
#
#                                                   # --- 2) Micro-cam relay: resilient loop + ClusterIP service ---
#                                                   cat > "${K8S_DIR}/relay.yaml" <<'YAML'
#                                                   apiVersion: apps/v1
#                                                   kind: Deployment
#                                                   metadata:
#                                                     name: micro-cam-relay
#                                                       namespace: suite
#                                                         labels: { app: micro-cam-relay }
#                                                         spec:
#                                                           replicas: 1
#                                                             selector: { matchLabels: { app: micro-cam-relay } }
#                                                               template:
#                                                                   metadata:
#                                                                         labels: { app: micro-cam-relay }
#                                                                             spec:
#                                                                                   containers:
#                                                                                         - name: ffmpeg
#                                                                                                 image: lscr.io/linuxserver/ffmpeg:latest
#                                                                                                         env:
#                                                                                                                   - name: SNAP_URL
#                                                                                                                               value: http://camera-uploader.suite.home.arpa/latest.jpg
#                                                                                                                                       command: ["/bin/sh","-lc"]
#                                                                                                                                               args:
#                                                                                                                                                         - |
#                                                                                                                                                                     set -e
#                                                                                                                                                                                 # wait for uploader to serve latest.jpg
#                                                                                                                                                                                             until wget -q --spider "$SNAP_URL"; do echo "waiting for $SNAP_URL"; sleep 2; done
#                                                                                                                                                                                                         # run forever; restart on error after short nap
#                                                                                                                                                                                                                     while true; do
#                                                                                                                                                                                                                                   ffmpeg -re -r 5 -f image2 -i "$SNAP_URL" \
#                                                                                                                                                                                                                                                        -vf "fps=5,format=yuv420p" \
#                                                                                                                                                                                                                                                                             -f rtsp rtsp://0.0.0.0:8554/porch || true
#                                                                                                                                                                                                                                                                                           echo "ffmpeg exited; retrying in 2s"
#                                                                                                                                                                                                                                                                                                         sleep 2
#                                                                                                                                                                                                                                                                                                                     done
#                                                                                                                                                                                                                                                                                                                             ports:
#                                                                                                                                                                                                                                                                                                                                       - containerPort: 8554
#                                                                                                                                                                                                                                                                                                                                                   name: rtsp
#                                                                                                                                                                                                                                                                                                                                                           readinessProbe:
#                                                                                                                                                                                                                                                                                                                                                                     tcpSocket: { port: 8554 }
#                                                                                                                                                                                                                                                                                                                                                                               initialDelaySeconds: 5
#                                                                                                                                                                                                                                                                                                                                                                                         periodSeconds: 5
#                                                                                                                                                                                                                                                                                                                                                                                         ---
#                                                                                                                                                                                                                                                                                                                                                                                         apiVersion: v1
#                                                                                                                                                                                                                                                                                                                                                                                         kind: Service
#                                                                                                                                                                                                                                                                                                                                                                                         metadata:
#                                                                                                                                                                                                                                                                                                                                                                                           name: micro-cam-relay
#                                                                                                                                                                                                                                                                                                                                                                                             namespace: suite
#                                                                                                                                                                                                                                                                                                                                                                                             spec:
#                                                                                                                                                                                                                                                                                                                                                                                               selector: { app: micro-cam-relay }
#                                                                                                                                                                                                                                                                                                                                                                                                 ports:
#                                                                                                                                                                                                                                                                                                                                                                                                     - name: rtsp
#                                                                                                                                                                                                                                                                                                                                                                                                           port: 8554
#                                                                                                                                                                                                                                                                                                                                                                                                                 targetPort: 8554
#                                                                                                                                                                                                                                                                                                                                                                                                                 YAML
#
#                                                                                                                                                                                                                                                                                                                                                                                                                 # --- 3) Traefik TCP route for RTSP to the relay ---
#                                                                                                                                                                                                                                                                                                                                                                                                                 cat > "${K8S_DIR}/micro-cam-relay-tcp.yaml" <<'YAML'
#                                                                                                                                                                                                                                                                                                                                                                                                                 apiVersion: traefik.containo.us/v1alpha1
#                                                                                                                                                                                                                                                                                                                                                                                                                 kind: IngressRouteTCP
#                                                                                                                                                                                                                                                                                                                                                                                                                 metadata:
#                                                                                                                                                                                                                                                                                                                                                                                                                   name: micro-cam-relay-tcp
#                                                                                                                                                                                                                                                                                                                                                                                                                     namespace: suite
#                                                                                                                                                                                                                                                                                                                                                                                                                     spec:
#                                                                                                                                                                                                                                                                                                                                                                                                                       entryPoints:
#                                                                                                                                                                                                                                                                                                                                                                                                                           - rtsp
#                                                                                                                                                                                                                                                                                                                                                                                                                             routes:
#                                                                                                                                                                                                                                                                                                                                                                                                                                 - match: HostSNI(`*`)
#                                                                                                                                                                                                                                                                                                                                                                                                                                       services:
#                                                                                                                                                                                                                                                                                                                                                                                                                                               - name: micro-cam-relay
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         port: 8554
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         YAML
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         # --- 4) Camera uploader PVC -> Longhorn (once installed) ---
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         # If you already have this file, we replace/ensure SC is longhorn
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         cat > "${K8S_DIR}/camera-uploader.yaml" <<'YAML'
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         apiVersion: v1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         kind: PersistentVolumeClaim
#                                                                                                                                                                                                                                                                                                                                                                                                                                                         metadata:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                           name: camera-uploader-pvc
#                                                                                                                                                                                                                                                                                                                                                                                                                                                             namespace: suite
#                                                                                                                                                                                                                                                                                                                                                                                                                                                             spec:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                               accessModes: ["ReadWriteOnce"]
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                 storageClassName: longhorn
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                   resources:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                       requests:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                             storage: 2Gi
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ---
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                             apiVersion: apps/v1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                             kind: Deployment
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                             metadata:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                               name: camera-uploader
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 namespace: suite
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   labels: { app: camera-uploader }
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   spec:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     replicas: 1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       selector: { matchLabels: { app: camera-uploader } }
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         template:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             metadata: { labels: { app: camera-uploader } }
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 spec:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       containers:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             - name: web
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     image: docker.io/allenwayne/camera-uploader:latest
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ports:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     - containerPort: 80
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             readinessProbe:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       httpGet: { path: /healthz, port: 80 }
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 initialDelaySeconds: 5
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           periodSeconds: 5
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   volumeMounts:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           - name: data
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     mountPath: /data
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           volumes:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 - name: data
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         persistentVolumeClaim:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   claimName: camera-uploader-pvc
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ---
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   apiVersion: v1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   kind: Service
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   metadata:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     name: camera-uploader
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       namespace: suite
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       spec:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         selector: { app: camera-uploader }
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ports:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               - name: http
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     port: 80
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           targetPort: 80
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ---
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           apiVersion: networking.k8s.io/v1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           kind: Ingress
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           metadata:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             name: camera-uploader
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               namespace: suite
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 annotations:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     kubernetes.io/ingress.class: traefik
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     spec:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       rules:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         - host: camera-uploader.suite.home.arpa
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             http:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   paths:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         - path: /
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 pathType: Prefix
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         backend:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   service:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               name: camera-uploader
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           port:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         number: 80
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         YAML
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         # --- 5) Longhorn installer + README (for Pi + NVMe + router USB backup) ---
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         cat > "${LONGHORN_DIR}/install-longhorn.sh" <<'BASH'
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         #!/usr/bin/env bash
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         set -euo pipefail
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         # 1) prereqs on every storage node (run via Ansible ideally)
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         # sudo apt-get update && sudo apt-get install -y open-iscsi nfs-common jq util-linux
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         # sudo systemctl enable --now iscsid
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         # 2) install longhorn
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         helm repo add longhorn https://charts.longhorn.io
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         helm repo update
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         kubectl create ns longhorn-system --dry-run=client -o yaml | kubectl apply -f -
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         helm upgrade --install longhorn longhorn/longhorn \
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           --namespace longhorn-system \
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             --set defaultSettings.defaultDataPath="/var/lib/longhorn" \
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               --set ingress.enabled=false
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               echo "Wait for longhorn pods..."
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               kubectl -n longhorn-system rollout status deploy/longhorn-ui
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               kubectl -n longhorn-system get pods -o wide
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               echo "Longhorn installed. Configure disks in UI or label nodes:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               kubectl label nodes w1 w2 w3 node.longhorn.io/create-default-disk=true --overwrite"
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               BASH
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               chmod +x "${LONGHORN_DIR}/install-longhorn.sh"
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               cat > "${DOCS_DIR}/README-longhorn.md" <<'MD'
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # Longhorn on Raspberry Pi cluster (best-practice quickstart)
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               **Why Longhorn:** lightweight, ARM-friendly, replicated volumes, NFS/S3 backups.
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ## Prep each storage node
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ```bash
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               sudo apt-get update
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               sudo apt-get install -y open-iscsi nfs-common jq util-linux
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               sudo systemctl enable --now iscsid
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # (Optional) dedicate a disk and mount it, e.g.:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # sudo mkfs.ext4 -F /dev/nvme0n1p1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # sudo mkdir -p /var/lib/longhorn/disks/nvme-01
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # echo '/dev/nvme0n1p1 /var/lib/longhorn/disks/nvme-01 ext4 noatime,nodiratime 0 2' | sudo tee -a /etc/fstab
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               # sudo mount -a
#
#
