apiVersion: batch/v1
kind: CronJob
metadata:
  name: homebridge-backup
  namespace: suite
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: alpine:3.20
              command: ["/bin/sh","-lc"]
              args:
                - |
                  set -eux
                  ts=$(date +%Y%m%d-%H%M%S)
                  tar -czf /backups/homebridge-$ts.tgz -C /homebridge .
                  echo "Wrote /backups/homebridge-$ts.tgz"
              volumeMounts:
                - { name: hb, mountPath: /homebridge }
                - { name: bkp, mountPath: /backups }
          volumes:
            - { name: hb,  persistentVolumeClaim: { claimName: homebridge-data } }
            - { name: bkp, persistentVolumeClaim: { claimName: homebridge-backups } }
