apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: suite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-cluster-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cluster-admin
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: suite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: suite
spec:
  selector: { matchLabels: { app: jenkins } }
  replicas: 1
  template:
    metadata: { labels: { app: jenkins } }
    spec:
      serviceAccountName: jenkins
      securityContext: { fsGroup: 1000 }
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk17
          imagePullPolicy: IfNotPresent
          env:
            - { name: JAVA_OPTS, value: "-Djenkins.install.runSetupWizard=false" }
          ports:
            - { containerPort: 8080, name: http }
            - { containerPort: 50000, name: agent }
          readinessProbe:
            httpGet: { path: /login, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /login, port: 8080 }
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests: { cpu: "500m", memory: "1Gi" }
            limits: { cpu: "1", memory: "2Gi" }
          volumeMounts:
            - { name: jenkins-home, mountPath: /var/jenkins_home }
      volumes:
        - name: jenkins-home
          persistentVolumeClaim: { claimName: jenkins-home }
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: suite
spec:
  selector: { app: jenkins }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
    - { name: agent, port: 50000, targetPort: 50000 }
  type: ClusterIP
